// Gerado automaticamente — NÃO editar manualmente
// Para atualizar: use o botão "Importar CSV" no painel
window.COMERCIAL_DATA = {
  snapshots: [
    {
      importedAt: "2026-05-11T10:24:34.939Z",
      label: "Mai/2026",
      source: "ativo-2026-05-11T10_24_34.939.csv",
      // c=conta, m=municipio, e=estado, a=areaComercial, ag=areaGrupo, p=porte(1/2/3), t=terminoUso, q=quantidade
      clientes: [
        {c:"Fundo Municipal de Saúde de Autazes",m:"Autazes",e:"AM",a:"Converge - AM",ag:"Converge - AM",p:2,t:"06/03/2031",q:41672},
        {c:"Prefeitura Municipal de Aspásia",m:"Aspásia",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"30/04/2026",q:1860},
        {c:"Fundo Municipal Saúde Xapuri",m:"Xapuri",e:"AC",a:"Status - AC",ag:"Status - AC",p:1,t:"19/12/2030",q:18181},
        {c:"Fundo Municipal de Saúde de Trairão",m:"Trairão",e:"PA",a:"Sistemática - PA",ag:"Sistemática - PA",p:1,t:"01/01/2031",q:18924},
        {c:"Prefeitura Municipal da Estância de Socorro",m:"Socorro",e:"SP",a:"CSM - SP (Campinas)",ag:"CSM - SP",p:2,t:"08/10/2035",q:40323},
        {c:"Prefeitura Municipal de Mesópolis",m:"Mesópolis",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"22/07/2030",q:1930},
        {c:"Fundo Municipal Saúde Palmitos",m:"Palmitos",e:"SC",a:"Guilherme Zamboni Ortigara",ag:"Guilherme Zamboni Ortigara",p:1,t:"01/02/2030",q:15627},
        {c:"Prefeitura Municipal Jambeiro",m:"Jambeiro",e:"SP",a:"Casp Vale - SP",ag:"Casp Vale - SP",p:1,t:"25/04/2030",q:6421},
        {c:"Prefeitura Municipal Andradas",m:"Andradas",e:"MG",a:"Sigma - MG",ag:"Sigma - MG",p:2,t:"11/04/2030",q:40522},
        {c:"Prefeitura Municipal Capitão Andrade",m:"Capitão Andrade",e:"MG",a:"Solução Tecnologia - MG",ag:"Solução Tecnologia - MG",p:1,t:"31/12/2026",q:4483},
        {c:"Fundo Municipal de Saúde de Modelo",m:"Modelo",e:"SC",a:"Guilherme Zamboni Ortigara",ag:"Guilherme Zamboni Ortigara",p:1,t:"27/06/2026",q:4085},
        {c:"Prefeitura Municipal de Nova Santa Bárbara",m:"Nova Santa Bárbara",e:"PR",a:"Publis - PR",ag:"Publis - PR",p:1,t:"27/02/2030",q:4183},
        {c:"Fundo Municipal Saúde Vidal Ramos",m:"Vidal Ramos",e:"SC",a:"Gean Carlos Omizzollo",ag:"Gean Carlos Omizzollo",p:1,t:"03/06/2029",q:6160},
        {c:"Prefeitura Municipal Estrela Velha",m:"Estrela Velha",e:"RS",a:"Delta - RS (Área 3)",ag:"Delta - RS",p:1,t:"02/01/2030",q:3066},
        {c:"Fundo Municipal Saúde Santa Cecília",m:"Santa Cecília",e:"SC",a:"Gean Carlos Omizzollo",ag:"Gean Carlos Omizzollo",p:1,t:"13/01/2041",q:15247},
        {c:"Prefeitura Municipal Santa Rosa de Viterbo",m:"Santa Rosa de Viterbo",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:1,t:"16/12/2029",q:23783},
        {c:"Fundo Municipal Saúde - SUS - Resende",m:"Resende",e:"RJ",a:"Custom - RJ",ag:"Custom - RJ",p:3,t:"31/12/2025",q:128460},
        {c:"Fundo Municipal de Saúde de Teixeirópolis",m:"Teixeirópolis",e:"RO",a:"Sispel - RO",ag:"Sispel - RO",p:1,t:"30/09/2034",q:4284},
        {c:"Fundo Municipal de Saúde de Candeias do Jamari",m:"Candeias do Jamari",e:"RO",a:"Sispel - RO",ag:"Sispel - RO",p:1,t:"01/01/2031",q:22564},
        {c:"Fundo Municipal Saúde Pinheiral",m:"Pinheiral",e:"RJ",a:"Custom - RJ",ag:"Custom - RJ",p:1,t:"31/12/2025",q:24553},
        {c:"Prefeitura Municipal de Três Fronteiras",m:"Três Fronteiras",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"06/10/2030",q:6802},
        {c:"Fundo Municipal de Saúde Batatais",m:"Batatais",e:"SP",a:"Sigma - MG (Parciais)",ag:"Sigma - MG",p:2,t:"10/10/2027",q:59342},
        {c:"Fundo Municipal Saúde Mondaí",m:"Mondaí",e:"SC",a:"Guilherme Zamboni Ortigara",ag:"Guilherme Zamboni Ortigara",p:1,t:"05/09/2026",q:9961},
        {c:"Prefeitura Municipal Natividade da Serra",m:"Natividade da Serra",e:"SP",a:"Casp Vale - SP",ag:"Casp Vale - SP",p:1,t:"03/01/2030",q:6963},
        {c:"Prefeitura Municipal de São João de Iracema",m:"São João de Iracema",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"15/07/2026",q:1843},
        {c:"Fundo Municipal Saúde Trombudo Central",m:"Trombudo Central",e:"SC",a:"Gean Carlos Omizzollo",ag:"Gean Carlos Omizzollo",p:1,t:"23/08/2027",q:7074},
        {c:"Município de Santa Fé do Sul",m:"Santa Fé do Sul",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:2,t:"19/10/2026",q:34762},
        {c:"Prefeitura Municipal de Rincão",m:"Rincão",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"14/10/2026",q:8731},
        {c:"Prefeitura Municipal Crissiumal",m:"Crissiumal",e:"RS",a:"Delta - RS (Área 4)",ag:"Delta - RS",p:1,t:"22/05/2026",q:12852},
        {c:"Prefeitura Municipal Arroio do Tigre",m:"Arroio do Tigre",e:"RS",a:"Delta - RS (Área 3)",ag:"Delta - RS",p:1,t:"09/10/2034",q:12022},
        {c:"Prefeitura Municipal de Bom Sucesso",m:"Bom Sucesso",e:"PR",a:"Prodasp - PR",ag:"Prodasp - PR",p:1,t:"12/08/2030",q:6583},
        {c:"Prefeitura Municipal Mata",m:"Mata",e:"RS",a:"Delta - RS (Área 3)",ag:"Delta - RS",p:1,t:"11/03/2031",q:4697},
        {c:"Prefeitura Municipal Sebastianópolis do Sul",m:"Sebastianópolis do Sul",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"11/04/2035",q:3184},
        {c:"Prefeitura Municipal Santana da Vargem",m:"Santana da Vargem",e:"MG",a:"Solução Tecnologia - MG",ag:"Solução Tecnologia - MG",p:1,t:"09/06/2027",q:6561},
        {c:"Fundo Municipal Saúde Novo Horizonte",m:"Novo Horizonte",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"01/07/2026",q:1},
        {c:"Prefeitura Municipal de Timóteo",m:"Timóteo",e:"MG",a:"Solução Tecnologia - MG",ag:"Solução Tecnologia - MG",p:2,t:"25/01/2027",q:77856},
        {c:"Prefeitura Municipal São José da Boa Vista",m:"São José da Boa Vista",e:"PR",a:"Theorema - PR",ag:"Theorema - PR",p:1,t:"16/12/2039",q:5968},
        {c:"Prefeitura Municipal Boa Vista das Missões",m:"Boa Vista das Missões",e:"RS",a:"Delta - RS (Área 4)",ag:"Delta - RS",p:1,t:"14/08/2026",q:1899},
        {c:"Prefeitura Municipal Cerrito",m:"Cerrito",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:1,t:"25/01/2027",q:5847},
        {c:"Prefeitura Municipal Jari",m:"Jari",e:"RS",a:"Delta - RS (Área 3)",ag:"Delta - RS",p:1,t:"01/12/2029",q:3349},
        {c:"Prefeitura Municipal Pinheirinho do Vale",m:"Pinheirinho do Vale",e:"RS",a:"Delta - RS (Área 4)",ag:"Delta - RS",p:1,t:"21/01/2027",q:4539},
        {c:"Prefeitura Municipal Boqueirão do Leão",m:"Boqueirão do Leão",e:"RS",a:"Delta - RS (Área 1)",ag:"Delta - RS",p:1,t:"10/08/2027",q:6231},
        {c:"Prefeitura Municipal Capão Bonito do Sul",m:"Capão Bonito do Sul",e:"RS",a:"Delta - RS (Área 1)",ag:"Delta - RS",p:1,t:"04/05/2026",q:1724},
        {c:"Município de Areias",m:"Areias",e:"SP",a:"Casp Vale - SP",ag:"Casp Vale - SP",p:1,t:"31/05/2028",q:3616},
        {c:"Prefeitura Municipal São José dos Ausentes",m:"São José dos Ausentes",e:"RS",a:"Delta - RS (Área 1)",ag:"Delta - RS",p:1,t:"01/10/2040",q:3128},
        {c:"Prefeitura Municipal Tenente Portela",m:"Tenente Portela",e:"RS",a:"Delta - RS (Área 4)",ag:"Delta - RS",p:1,t:"21/09/2030",q:14494},
        {c:"Prefeitura Municipal São Simão",m:"São Simão",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:1,t:"23/01/2031",q:13374},
        {c:"Prefeitura Municipal Santiago",m:"Santiago",e:"RS",a:"Delta - RS (Área 3)",ag:"Delta - RS",p:2,t:"31/12/2034",q:48959},
        {c:"Fundo Municipal Saúde Entre Rios",m:"Entre Rios",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"02/12/2034",q:3322},
        {c:"Fundo Municipal Saúde Passos Maia",m:"Passos Maia",e:"SC",a:"Francis Spada",ag:"Francis Spada",p:1,t:"09/04/2035",q:4025},
        {c:"Fundo Municipal Saúde Anita Garibaldi",m:"Anita Garibaldi",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"30/04/2026",q:8286},
        {c:"Fundo Municipal Saúde Imbuia",m:"Imbuia",e:"SC",a:"Gean Carlos Omizzollo",ag:"Gean Carlos Omizzollo",p:1,t:"01/01/2040",q:5988},
        {c:"Prefeitura Municipal de Sabáudia",m:"Sabáudia",e:"PR",a:"Publis - PR",ag:"Publis - PR",p:1,t:"04/10/2026",q:8819},
        {c:"Prefeitura Municipal São Jerônimo da Serra",m:"São Jerônimo da Serra",e:"PR",a:"Vista Sistemas - PR",ag:"Vista Sistemas - PR",p:1,t:"03/10/2026",q:10742},
        {c:"Prefeitura Municipal Inajá",m:"Inajá",e:"PR",a:"Prodasp - PR",ag:"Prodasp - PR",p:1,t:"02/09/2026",q:2529},
        {c:"Prefeitura Municipal Santo Antônio do Paraíso",m:"Santo Antônio do Paraíso",e:"PR",a:"Vista Sistemas - PR",ag:"Vista Sistemas - PR",p:1,t:"07/07/2036",q:2122},
        {c:"Fundo Municipal Saúde Abdon Batista",m:"Abdon Batista",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"09/03/2027",q:2600},
        {c:"Fundo Municipal Saúde São José do Cerrito",m:"São José do Cerrito",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"01/07/2040",q:8708},
        {c:"Prefeitura Municipal Alto Paraná",m:"Alto Paraná",e:"PR",a:"Prodasp - PR",ag:"Prodasp - PR",p:1,t:"29/05/2030",q:13897},
        {c:"Prefeitura Municipal Vargem Bonita",m:"Vargem Bonita",e:"SC",a:"Francis Spada",ag:"Francis Spada",p:1,t:"16/04/2035",q:4572},
        {c:"Prefeitura Municipal Morrinhos do Sul",m:"Morrinhos do Sul",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:1,t:"02/01/2028",q:3091},
        {c:"Prefeitura Municipal Ponte Alta do Norte",m:"Ponte Alta do Norte",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"17/03/2036",q:3217},
        {c:"Prefeitura Municipal Vista Alegre",m:"Vista Alegre",e:"RS",a:"Delta - RS (Área 4)",ag:"Delta - RS",p:1,t:"16/12/2034",q:2655},
        {c:"Fundo Municipal Saúde Lindóia do Sul",m:"Lindóia do Sul",e:"SC",a:"Francis Spada",ag:"Francis Spada",p:1,t:"30/06/2035",q:4549},
        {c:"Prefeitura Municipal Jacuizinho",m:"Jacuizinho",e:"RS",a:"Delta - RS (Área 3)",ag:"Delta - RS",p:1,t:"04/11/2030",q:2028},
        {c:"Prefeitura Municipal de Nhandeara",m:"Nhandeara",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"30/09/2041",q:9670},
        {c:"Prefeitura Municipal Mampituba",m:"Mampituba",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:1,t:"15/09/2027",q:2954},
        {c:"Prefeitura Analândia",m:"Analândia",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:1,t:"30/08/2024",q:4577},
        {c:"Fundo Municipal Saúde São Joaquim",m:"São Joaquim",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:2,t:"02/05/2028",q:26026},
        {c:"Prefeitura Municipal Torres",m:"Torres",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:2,t:"23/01/2028",q:41709},
        {c:"Prefeitura Municipal de Serra Azul",m:"Serra Azul",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:1,t:"10/05/2027",q:10429},
        {c:"Prefeitura Municipal Santana do Itararé",m:"Santana do Itararé",e:"PR",a:"Vista Sistemas - PR",ag:"Vista Sistemas - PR",p:1,t:"11/06/2026",q:5514},
        {c:"Fundo Municipal Saúde Grão Pará",m:"Grão Pará",e:"SC",a:"Heleno Constante Pacheco",ag:"Heleno Constante Pacheco",p:1,t:"07/10/2030",q:6149},
        {c:"Fundo Municipal Saúde Matos Costa",m:"Matos Costa",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"14/11/2030",q:2762},
        {c:"Prefeitura Municipal Brunópolis",m:"Brunópolis",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"26/04/2027",q:2488},
        {c:"Prefeitura Municipal Capão do Leão",m:"Capão do Leão",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:2,t:"04/11/2027",q:27071},
        {c:"Prefeitura Municipal Armazém",m:"Armazém",e:"SC",a:"Heleno Constante Pacheco",ag:"Heleno Constante Pacheco",p:1,t:"01/12/2027",q:8825},
        {c:"Fundo Municipal Saúde Presidente Castello Branco",m:"Presidente Castello Branco",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"24/08/2026",q:1692},
        {c:"Prefeitura Municipal Constantina",m:"Constantina",e:"RS",a:"Delta - RS (Área 4)",ag:"Delta - RS",p:1,t:"10/08/2027",q:10383},
        {c:"Fundo Municipal de Saúde de Irati",m:"Irati",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"20/12/2029",q:2069},
        {c:"Prefeitura Municipal Santo Antônio do Caiuá",m:"Santo Antônio do Caiuá",e:"PR",a:"Prodasp - PR",ag:"Prodasp - PR",p:1,t:"19/09/2027",q:2499},
        {c:"Prefeitura Municipal Santa Gertrudes",m:"Santa Gertrudes",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:1,t:"06/11/2028",q:23721},
        {c:"Prefeitura Municipal Sertão Santana",m:"Sertão Santana",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:1,t:"17/06/2026",q:6062},
        {c:"Fundo Municipal Saúde Major Vieira",m:"Major Vieira",e:"SC",a:"Gean Carlos Omizzollo",ag:"Gean Carlos Omizzollo",p:1,t:"07/01/2031",q:7359},
        {c:"Prefeitura Municipal de São Carlos do Ivaí",m:"São Carlos do Ivaí",e:"PR",a:"Prodasp - PR",ag:"Prodasp - PR",p:1,t:"08/08/2035",q:6588},
        {c:"Prefeitura Municipal Monte Castelo",m:"Monte Castelo",e:"SC",a:"Gean Carlos Omizzollo",ag:"Gean Carlos Omizzollo",p:1,t:"07/01/2031",q:7754},
        {c:"Prefeitura Municipal São Jerônimo",m:"São Jerônimo",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:1,t:"18/06/2034",q:20909},
        {c:"Prefeitura Municipal de Planura",m:"Planura",e:"MG",a:"Sigma - MG",ag:"Sigma - MG",p:1,t:"31/05/2026",q:10503},
        {c:"Fundo Municipal Saúde Capão Alto",m:"Capão Alto",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"10/09/2026",q:2892},
        {c:"Prefeitura Municipal Arroio do Padre",m:"Arroio do Padre",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:1,t:"03/01/2030",q:2638},
        {c:"Prefeitura Municipal Pinhalão",m:"Pinhalão",e:"PR",a:"Theorema - PR",ag:"Theorema - PR",p:1,t:"18/02/2027",q:6564},
        {c:"Fundo Municipal Saúde Bom Jesus",m:"Bom Jesus",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"18/11/2034",q:2721},
        {c:"Fundo Municipal Saúde Flor do Sertão",m:"Flor do Sertão",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"01/01/2035",q:1784},
        {c:"Prefeitura Terra Roxa",m:"Terra Roxa",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"15/05/2040",q:7903},
        {c:"Prefeitura Municipal de Nova Luzitânia",m:"Nova Luzitânia",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"04/09/2026",q:2837},
        {c:"Prefeitura Municipal Boa Vista do Incra",m:"Boa Vista do Incra",e:"RS",a:"Delta - RS (Área 4)",ag:"Delta - RS",p:1,t:"17/10/2027",q:2267},
        {c:"Prefeitura Municipal Fontoura Xavier",m:"Fontoura Xavier",e:"RS",a:"Delta - RS (Área 1)",ag:"Delta - RS",p:1,t:"",q:9573},
        {c:"Prefeitura Municipal de Planalto",m:"Planalto",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"07/02/2034",q:4392},
        {c:"Prefeitura Municipal de Gastão Vidigal",m:"Gastão Vidigal",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"04/11/2028",q:3234},
        {c:"Prefeitura Municipal de União da Vitória",m:"União da Vitória",e:"PR",a:"Vella - PR",ag:"Vella - PR",p:2,t:"01/12/2027",q:55238},
        {c:"Prefeitura Municipal de Nipoã",m:"Nipoã",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"20/02/2030",q:4756},
        {c:"Fundo Municipal Saúde Coronel Martins",m:"Coronel Martins",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"29/05/2026",q:2069},
        {c:"Fundo Municipal Saúde São Domingos",m:"São Domingos",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"13/07/2035",q:8984},
        {c:"Prefeitura Municipal Taquaral",m:"Taquaral",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:1,t:"25/02/2041",q:2620},
        {c:"Prefeitura da Estância de Atibaia",m:"Atibaia",e:"SP",a:"Grandes Contas - (CSM)",ag:"Grandes Contas - (CSM)",p:3,t:"03/02/2030",q:171672},
        {c:"Prefeitura Municipal Novo Tiradentes",m:"Novo Tiradentes",e:"RS",a:"Delta - RS (Área 4)",ag:"Delta - RS",p:1,t:"01/02/2038",q:2115},
        {c:"Fundo Municipal Saúde São Miguel do Oeste",m:"São Miguel do Oeste",e:"SC",a:"Guilherme Zamboni Ortigara",ag:"Guilherme Zamboni Ortigara",p:2,t:"30/06/2026",q:43946},
        {c:"Prefeitura Municipal Barão do Triunfo",m:"Barão do Triunfo",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:1,t:"13/03/2031",q:5893},
        {c:"Fundo Municipal Saúde Saltinho",m:"Saltinho",e:"SC",a:"Guilherme Zamboni Ortigara",ag:"Guilherme Zamboni Ortigara",p:1,t:"05/04/2027",q:3626},
        {c:"Prefeitura Municipal Cerro Azul",m:"Cerro Azul",e:"PR",a:"Vella - PR",ag:"Vella - PR",p:1,t:"05/01/2031",q:16145},
        {c:"Prefeitura Municipal de Ipiguá",m:"Ipiguá",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"20/01/2025",q:6551},
        {c:"Município de Barra do Quaraí",m:"Barra do Quaraí",e:"RS",a:"Delta - RS (Área 3)",ag:"Delta - RS",p:1,t:"23/06/2035",q:4053},
        {c:"Prefeitura Municipal de Neves Paulista",m:"Neves Paulista",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"26/04/2026",q:9719},
        {c:"Prefeitura Municipal Alfredo Wagner",m:"Alfredo Wagner",e:"SC",a:"Digital - SC",ag:"Digital - SC",p:1,t:"01/01/2028",q:10455},
        {c:"Prefeitura General Salgado",m:"General Salgado",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"27/08/2040",q:10301},
        {c:"Fundo Municipal da Saúde de Coronel Freitas",m:"Coronel Freitas",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"28/04/2041",q:10303},
        {c:"Prefeitura Municipal de Monte Alegre dos Campos",m:"Monte Alegre dos Campos",e:"RS",a:"Delta - RS (Área 1)",ag:"Delta - RS",p:1,t:"30/06/2026",q:3610},
        {c:"Prefeitura Municipal de Turiúba",m:"Turiúba",e:"SP",a:"BW Sistemas - SP",ag:"BW Sistemas - SP",p:1,t:"",q:1798},
        {c:"Prefeitura Municipal de Nepomuceno",m:"Nepomuceno",e:"MG",a:"ASI - MG",ag:"ASI - MG",p:1,t:"30/06/2027",q:24869},
        {c:"Prefeitura Municipal Pinhal da Serra",m:"Pinhal da Serra",e:"RS",a:"Delta - RS (Área 1)",ag:"Delta - RS",p:1,t:"03/08/2026",q:2243},
        {c:"Prefeitura Municipal Orlândia",m:"Orlândia",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:2,t:"16/09/2030",q:37916},
        {c:"Prefeitura Municipal Wenceslau Braz",m:"Wenceslau Braz",e:"PR",a:"Theorema - PR",ag:"Theorema - PR",p:1,t:"28/07/2037",q:18894},
        {c:"Fundo Municipal Saúde Água Doce",m:"Água Doce",e:"SC",a:"Francis Spada",ag:"Francis Spada",p:1,t:"01/11/2040",q:6286},
        {c:"Fundo Municipal Saúde Otacílio Costa",m:"Otacílio Costa",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"02/12/2035",q:17357},
        {c:"Fundo Municipal Saúde Urubici",m:"Urubici",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"17/10/2026",q:11156},
        {c:"Prefeitura Municipal Cerro Grande do Sul",m:"Cerro Grande do Sul",e:"RS",a:"Delta - RS (Área 5)",ag:"Delta - RS",p:1,t:"29/07/2026",q:9054},
        {c:"Prefeitura Municipal Cássia dos Coqueiros",m:"Cássia dos Coqueiros",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:1,t:"26/05/2026",q:2777},
        {c:"Fundo Municipal Saúde Monte Carlo",m:"Monte Carlo",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"06/06/2035",q:9131},
        {c:"Prefeitura Municipal Iracema do Oeste",m:"Iracema do Oeste",e:"PR",a:"Espyl - PR",ag:"Espyl - PR",p:1,t:"01/07/2026",q:2347},
        {c:"Fundo Municipal Saúde Xaxim",m:"Xaxim",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:2,t:"06/09/2027",q:141},
        {c:"Fundo Municipal Saúde Celso Ramos",m:"Celso Ramos",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"10/09/2034",q:2802},
        {c:"Prefeitura Municipal de Itaguara",m:"Itaguara",e:"MG",a:"ASI - MG",ag:"ASI - MG",p:1,t:"21/02/2029",q:14408},
        {c:"Fundo Municipal Saúde Macieira",m:"Macieira",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"17/04/2035",q:1778},
        {c:"Prefeitura Municipal Sertaneja",m:"Sertaneja",e:"PR",a:"Theorema - PR",ag:"Theorema - PR",p:1,t:"17/08/2026",q:5761},
        {c:"Fundo Municipal Saúde Santo Amaro da Imperatriz",m:"Santo Amaro da Imperatriz",e:"SC",a:"Adonis Fernandes",ag:"Adonis Fernandes",p:2,t:"11/01/2028",q:28260},
        {c:"Prefeitura Municipal de Assaí",m:"Assaí",e:"PR",a:"Publis - PR",ag:"Publis - PR",p:1,t:"03/06/2026",q:17628},
        {c:"Prefeitura Municipal Ortigueira",m:"Ortigueira",e:"PR",a:"Vista Sistemas - PR",ag:"Vista Sistemas - PR",p:2,t:"26/02/2031",q:26078},
        {c:"Fundo Municipal Saúde Santa Cruz do Sul",m:"Santa Cruz do Sul",e:"RS",a:"Grandes Contas - (JLA)",ag:"Grandes Contas - (JLA)",p:3,t:"14/03/2028",q:133136},
        {c:"Prefeitura Municipal Guaranésia",m:"Guaranésia",e:"MG",a:"Sigma - MG",ag:"Sigma - MG",p:1,t:"31/12/2026",q:19209},
        {c:"Prefeitura Municipal Mallet",m:"Mallet",e:"PR",a:"Vella - PR",ag:"Vella - PR",p:1,t:"15/12/2030",q:13378},
        {c:"Fundo Municipal Saúde Capinzal",m:"Capinzal",e:"SC",a:"Francis Spada",ag:"Francis Spada",p:1,t:"06/02/2031",q:23184},
        {c:"Prefeitura Municipal Frei Rogério",m:"Frei Rogério",e:"SC",a:"Gean Carlos Omizzollo",ag:"Gean Carlos Omizzollo",p:1,t:"17/03/2036",q:2411},
        {c:"Prefeitura Municipal Cornélio Procópio",m:"Cornélio Procópio",e:"PR",a:"Publis - PR",ag:"Publis - PR",p:2,t:"29/09/2026",q:44599},
        {c:"Prefeitura Municipal Itiquira",m:"Itiquira",e:"MT",a:"Staf Sistemas - MT",ag:"Staf Sistemas - MT",p:1,t:"15/03/2028",q:11856},
        {c:"Prefeitura Municipal Salto do Itararé",m:"Salto do Itararé",e:"PR",a:"Vista Sistemas - PR",ag:"Vista Sistemas - PR",p:1,t:"18/03/2030",q:5195},
        {c:"Fundo Municipal Saúde Lacerdópolis",m:"Lacerdópolis",e:"SC",a:"Francis Spada",ag:"Francis Spada",p:1,t:"24/04/2027",q:2256},
        {c:"Prefeitura Municipal de Dois Córregos",m:"Dois Córregos",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:1,t:"07/12/2026",q:24170},
        {c:"Prefeitura Municipal Serrana",m:"Serrana",e:"SP",a:"CSM - SP",ag:"CSM - SP",p:2,t:"03/02/2026",q:44495},
        {c:"Prefeitura Municipal Figueira",m:"Figueira",e:"PR",a:"Vista Sistemas - PR",ag:"Vista Sistemas - PR",p:1,t:"01/12/2026",q:8064},
        {c:"Prefeitura Municipal Nova Fátima",m:"Nova Fátima",e:"PR",a:"Theorema - PR",ag:"Theorema - PR",p:1,t:"15/04/2031",q:7225},
        {c:"Prefeitura Municipal de Maracaju",m:"Maracaju",e:"MS",a:"Staf Sistemas - MS",ag:"Staf Sistemas - MS",p:2,t:"09/09/2026",q:43247},
        {c:"Fundo Municipal Saúde Congonhinhas",m:"Congonhinhas",e:"PR",a:"Vista Sistemas - PR",ag:"Vista Sistemas - PR",p:1,t:"22/11/2026",q:8336},
        {c:"Prefeitura Municipal Ponte Alta",m:"Ponte Alta",e:"SC",a:"Eduardo Pereira",ag:"Eduardo Pereira",p:1,t:"02/10/2030",q:4437},
        {c:"Prefeitura Municipal Agudos do Sul",m:"Agudos do Sul",e:"PR",a:"Vella - PR",ag:"Vella - PR",p:1,t:"03/01/2031",q:10092},
        {c:"Prefeitura Municipal Rancho Queimado",m:"Rancho Queimado",e:"SC",a:"Adonis Fernandes",ag:"Adonis Fernandes",p:1,t:"23/04/2029",q:3252},
        {c:"Fundo Municipal Saúde Jaborá",m:"Jaborá",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"07/07/2035",q:4314},
        {c:"Fundo Municipal Saúde Xavantina",m:"Xavantina",e:"SC",a:"FAEE - SC",ag:"FAEE - SC",p:1,t:"13/06/2030",q:3654},
        {c:"Fundo Municipal Saúde Ipira",m:"Ipira",e:"SC",a:"Francis Spada",ag:"Francis Spada",p:1,t:"08/07/2035",q:4580}
      ]
    }
  ]
};
